# Generated by Django 2.2 on 2023-12-05 05:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20231205_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
