# Generated by Django 2.2 on 2023-12-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_router'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.FileField(upload_to='InfoFiles')),
            ],
        ),
        migrations.DeleteModel(
            name='Router',
        ),
    ]
