# Generated by Django 2.2 on 2023-12-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20231206_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoFiles',
            new_name='InfoFile',
        ),
    ]
