# Generated by Django 2.2 on 2023-12-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_notes_notesfile_papers_papersfile_ynu_ynufile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoFile',
            new_name='HomeFile',
        ),
    ]
