# Generated by Django 2.2 on 2023-12-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20231206_2220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Home',
        ),
    ]
