# Generated by Django 2.2 on 2023-12-07 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_closedfriends_closedfriendsfile_lanping_lanpingfile_misc_miscfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Info',
        ),
        migrations.DeleteModel(
            name='ClosedFriends',
        ),
        migrations.DeleteModel(
            name='ClosedFriendsFile',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='HomeFile',
        ),
        migrations.DeleteModel(
            name='Lanping',
        ),
        migrations.DeleteModel(
            name='LanpingFile',
        ),
        migrations.DeleteModel(
            name='Misc',
        ),
        migrations.DeleteModel(
            name='MiscFile',
        ),
        migrations.DeleteModel(
            name='NotesFile',
        ),
        migrations.DeleteModel(
            name='Papers',
        ),
        migrations.DeleteModel(
            name='PapersFile',
        ),
        migrations.DeleteModel(
            name='YNU',
        ),
        migrations.DeleteModel(
            name='YNUFile',
        ),
    ]
