# Generated by Django 2.2 on 2023-12-07 00:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20231207_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infooo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
