# Generated by Django 2.2 on 2023-12-07 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_auto_20231207_0816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infooo',
            new_name='Info',
        ),
    ]
